# Generated by Django 5.0.4 on 2024-04-19 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Escola', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atividade',
            name='id_professor',
        ),
        migrations.AddField(
            model_name='atividade',
            name='id_turma',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='App_Escola.turma'),
        ),
    ]
